name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  _setup: &node-setup
    uses: actions/setup-node@v4
    with:
      node-version: 22.11.0
      cache: 'npm'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *node-setup
      - run: npm ci
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *node-setup
      - run: npm ci
      - run: npm run check-types

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *node-setup
      - run: npm ci
      - run: npm run test

  secretlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - *node-setup
      - run: npm ci
      - run: npm run secretlint
